### ISSUE TITLE
Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer

### ISSUE THREAD

**Issue by jjmaciasdev** [bufferapp/android-clean-architecture-mvi-boilerplate#3]
Trying run in Emulator: Nexus 5 with Android 4.4 x86

12-26 10:25:33.999 4036-4036/org.buffer.android.boilerplate.ui E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                 Process: org.buffer.android.boilerplate.ui, PID: 4036
                                                                                 java.lang.RuntimeException: Unable to get provider android.arch.lifecycle.ProcessLifecycleOwnerInitializer: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/data/app/org.buffer.android.boilerplate.ui-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.buffer.android.boilerplate.ui-1, /vendor/lib, /system/lib]]
                                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4793)
                                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385)
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325)
                                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                     at android.os.Looper.loop(Looper.java:136)
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017)
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515)
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
                                                                                     at dalvik.system.NativeStart.main(Native Method)
                                                                                  Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.ProcessLifecycleOwnerInitializer" on path: DexPathList[[zip file "/data/app/org.buffer.android.boilerplate.ui-1.apk"],nativeLibraryDirectories=[/data/app-lib/org.buffer.android.boilerplate.ui-1, /vendor/lib, /system/lib]]
                                                                                     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                                                                                     at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                                                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4778)
                                                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4385) 
                                                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4325) 
                                                                                     at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                                                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                                                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                     at android.os.Looper.loop(Looper.java:136) 
                                                                                     at android.app.ActivityThread.main(ActivityThread.java:5017) 
                                                                                     at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                                     at java.lang.reflect.Method.invoke(Method.java:515) 
                                                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
                                                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
                                                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by musabgultekin** [comment]
Try disabling Instant Run
